version: "3.9"
services:
  mainnetwork:
    image: alpine:3.14
    command: ["tail", "-f", "/dev/null"]
  db:
    image: postgres:13-alpine
    volumes:
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
      - ./database/script:/script:ro
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  backend:
    image: python:3.12
    working_dir: /app
    command: ["./start.sh"]
    volumes:
      - ./backend:/app:delegated
    environment:
      - DB_SCHEMA=african_bamboo_dashboard
      - DB_USER=akvo
      - DB_PASSWORD=password
      - DB_HOST=db
      - DEBUG=True
      - SECRET_KEY=${SECRET_KEY}
      - COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN:-}
      - MAILJET_APIKEY=$MAILJET_APIKEY
      - MAILJET_SECRET=$MAILJET_SECRET
      - WEBDOMAIN=$WEBDOMAIN
    depends_on:
      - db
  frontend:
    image: akvo/akvo-node-20-alpine:20250923.063900.7ce4b53
    command: ["./start.sh"]
    volumes:
      - ./frontend:/app:delegated
    working_dir: /app
    environment:
      - WEBDOMAIN=${WEBDOMAIN}
      - SESSION_SECRET=${SESSION_SECRET}
      - NEXT_PUBLIC_MAPBOX_TOKEN=${NEXT_PUBLIC_MAPBOX_TOKEN}
      - NEXT_PUBLIC_SUPPORT_EMAIL=${NEXT_PUBLIC_SUPPORT_EMAIL}
    depends_on:
      - backend
volumes:
  pg-data:
