name: Reusable Build & Test

on:
  workflow_call:
    outputs:
      test_result:
        description: "The result of the test job (success or failure)"
        value: ${{ jobs.test.outputs.test_result }}

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    outputs:
      test_result: ${{ steps.test_script.outcome }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set short git commit SHA
        id: vars
        run: |
          shortSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$shortSha" >> $GITHUB_ENV

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: Set CI variables
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "CI_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
            echo "PULL_REQUEST_EVENT=true" >> $GITHUB_ENV
          else
            echo "CI_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
            echo "PULL_REQUEST_EVENT=false" >> $GITHUB_ENV
          fi
          echo "CI_TAG=${{ github.ref_type == 'tag' && github.ref_name || '' }}" >> $GITHUB_ENV

      - name: Test
        id: test_script
        env:
          CI_COMMIT: ${{ env.COMMIT_SHORT_SHA }}
          CI_BRANCH: ${{ env.CI_BRANCH }}
          CI_TAG: ${{ env.CI_TAG }}
          CI_PULL_REQUEST: ${{ env.PULL_REQUEST_EVENT }}
          COMPOSE_INTERACTIVE_NO_CLI: 1
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          DBDOCS_TOKEN: ${{ secrets.DBDOCS_TOKEN }}
          WEBDOMAIN: ${{ secrets.WEBDOMAIN }}
          NEXT_AUTH_SECRET_KEY: ${{ secrets.NEXT_AUTH_SECRET_KEY }}
        run: |
          ./ci/test.sh

      - name: Upload coverage to Coveralls
        if: steps.test_script.outcome == 'success'
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./backend/coverage.lcov
          fail-on-error: false
